on:
  push:
    branches:
      - release-please--**
name: 'Build & Push Dist'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVEX_BOT_TOKEN }}

      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: update README
        run: |-
          MAJOR_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[", ]//g' \
            | awk -F. '{ print $1 }')
          sed -i "s/\(uses: OctopusDeploy\/install-octopus-cli-action@\).*/\1v${MAJOR_VERSION}/g" README.md

      - name: commit
        run: |-
          git config --global user.name "team-github-bot"
          git config user.email 'team-github-bot@octopus.com'
          git add README.md
          git add dist/
          git diff-index --quiet HEAD || (git commit -m "chore: build dist and update README" && git push origin)
